-- Automania weekly patch 2026-07-06
-- Generated by automated weekly car-market research sweep.
-- Current DB: 65 rows (max id = 65). New rows use ids 66-75.
-- Prices marked ESTIMATED are not yet confirmed for the Qatar market -- verify before relying on them commercially.
-- Review every row before applying to production. Nothing here has been auto-applied.

-- ============================================================
-- SECTION 1: New car discoveries (not yet in the `cars` table)
-- ============================================================

-- BYD Atto 8 -- all-new 3-row electric SUV, confirmed arriving in GCC showrooms.
-- Price ESTIMATED (~QAR 210,000) based on comparable 3-row EV SUVs already in DB (Denza D9, Hyundai IONIQ 9).
INSERT INTO cars (id, brand, model, type, badge, price, upcoming)
VALUES (66, 'BYD', 'Atto 8', 'suv', 'EV', 210000, true)
ON CONFLICT (id) DO UPDATE SET
  brand = EXCLUDED.brand, model = EXCLUDED.model, type = EXCLUDED.type,
  badge = EXCLUDED.badge, price = EXCLUDED.price, upcoming = EXCLUDED.upcoming;

-- iCaur V27 -- new Chinese sub-brand, range-extended EV (REEV), Abu Dhabi showroom opened.
-- Price TBC -- no confirmed figure found; using PHEV badge as closest match to REEV drivetrain.
INSERT INTO cars (id, brand, model, type, badge, price, upcoming)
VALUES (67, 'iCaur', 'V27', 'chinese', 'PHEV', 145000, true)
ON CONFLICT (id) DO UPDATE SET
  brand = EXCLUDED.brand, model = EXCLUDED.model, type = EXCLUDED.type,
  badge = EXCLUDED.badge, price = EXCLUDED.price, upcoming = EXCLUDED.upcoming;

-- Tesla Model Y L Premium -- new 6-seat variant, UAE deliveries from Nov 2026. Tesla has no prior entry in DB.
-- Price converted from AED 224,990 (~QAR 225,000 at near 1:1 AED:QAR parity). Qatar launch timing TBC.
INSERT INTO cars (id, brand, model, type, badge, price, upcoming)
VALUES (68, 'Tesla', 'Model Y L Premium', 'suv', 'EV', 225000, true)
ON CONFLICT (id) DO UPDATE SET
  brand = EXCLUDED.brand, model = EXCLUDED.model, type = EXCLUDED.type,
  badge = EXCLUDED.badge, price = EXCLUDED.price, upcoming = EXCLUDED.upcoming;

-- BMW i3 (Neue Klasse) -- flagship EV on new 800V platform. BMW has no prior entry in DB.
-- Price ESTIMATED -- no confirmed GCC figure found.
INSERT INTO cars (id, brand, model, type, badge, price, upcoming)
VALUES (69, 'BMW', 'i3 (Neue Klasse)', 'ev', 'EV', 220000, true)
ON CONFLICT (id) DO UPDATE SET
  brand = EXCLUDED.brand, model = EXCLUDED.model, type = EXCLUDED.type,
  badge = EXCLUDED.badge, price = EXCLUDED.price, upcoming = EXCLUDED.upcoming;

-- Mercedes C-Class Electric -- launching summer 2026. Mercedes has no prior entry in DB.
-- Price ESTIMATED -- no confirmed GCC figure found.
INSERT INTO cars (id, brand, model, type, badge, price, upcoming)
VALUES (70, 'Mercedes-Benz', 'C-Class Electric', 'sedan', 'EV', 240000, true)
ON CONFLICT (id) DO UPDATE SET
  brand = EXCLUDED.brand, model = EXCLUDED.model, type = EXCLUDED.type,
  badge = EXCLUDED.badge, price = EXCLUDED.price, upcoming = EXCLUDED.upcoming;

-- Lucid Cosmos -- Saudi-built premium EV, targeted "under $50,000". Lucid has no prior entry in DB.
-- Price converted from ~$50,000 USD x 3.64 = ~QAR 182,000 (upper bound estimate).
INSERT INTO cars (id, brand, model, type, badge, price, upcoming)
VALUES (71, 'Lucid', 'Cosmos', 'luxury', 'EV', 182000, true)
ON CONFLICT (id) DO UPDATE SET
  brand = EXCLUDED.brand, model = EXCLUDED.model, type = EXCLUDED.type,
  badge = EXCLUDED.badge, price = EXCLUDED.price, upcoming = EXCLUDED.upcoming;

-- Toyota Rush 2026 -- compact 7-seat GCC-spec SUV. Not currently in DB.
-- Price ESTIMATED -- no confirmed GCC figure found.
INSERT INTO cars (id, brand, model, type, badge, price, upcoming)
VALUES (72, 'Toyota', 'Rush 2026', 'suv', NULL, 78000, false)
ON CONFLICT (id) DO UPDATE SET
  brand = EXCLUDED.brand, model = EXCLUDED.model, type = EXCLUDED.type,
  badge = EXCLUDED.badge, price = EXCLUDED.price, upcoming = EXCLUDED.upcoming;

-- Hyundai Palisade (all-new 2026) -- redesigned large SUV w/ available hybrid. Not currently in DB.
-- Price ESTIMATED -- no confirmed GCC figure found.
INSERT INTO cars (id, brand, model, type, badge, price, upcoming)
VALUES (73, 'Hyundai', 'Palisade 2026', 'suv', 'Hybrid', 195000, true)
ON CONFLICT (id) DO UPDATE SET
  brand = EXCLUDED.brand, model = EXCLUDED.model, type = EXCLUDED.type,
  badge = EXCLUDED.badge, price = EXCLUDED.price, upcoming = EXCLUDED.upcoming;

-- Hyundai Staria Electric -- first full EV variant of the Staria MPV. Not currently in DB (no Hyundai MPV listed).
-- Price ESTIMATED -- no confirmed GCC figure found.
INSERT INTO cars (id, brand, model, type, badge, price, upcoming)
VALUES (74, 'Hyundai', 'Staria Electric', 'mpv', 'EV', 175000, true)
ON CONFLICT (id) DO UPDATE SET
  brand = EXCLUDED.brand, model = EXCLUDED.model, type = EXCLUDED.type,
  badge = EXCLUDED.badge, price = EXCLUDED.price, upcoming = EXCLUDED.upcoming;

-- BYD Seal 07 -- distinct sedan from the existing BYD Seal (id 17). Listed "Coming Soon" on Qatar dealer sites.
-- Price TBC -- no confirmed figure found.
INSERT INTO cars (id, brand, model, type, badge, price, upcoming)
VALUES (75, 'BYD', 'Seal 07', 'sedan', 'EV', 155000, true)
ON CONFLICT (id) DO UPDATE SET
  brand = EXCLUDED.brand, model = EXCLUDED.model, type = EXCLUDED.type,
  badge = EXCLUDED.badge, price = EXCLUDED.price, upcoming = EXCLUDED.upcoming;

-- ============================================================
-- SECTION 2: Status / price updates
-- ============================================================
-- No confirmed Qatar-specific launch or price-change evidence was found this week for existing
-- `upcoming=true` rows (ids 6,7,8,9,10,42,60,61,62,63,64,65). No UPDATE statements are included
-- to avoid marking cars "available" without a verified source. Manual verification recommended for
-- ids 6-10 (still tagged with "2025" in the model name despite being mid-2026).
--
-- Hongqi H9 / HS7 (ids 53, 54) launch is already correctly reflected as upcoming=false -- no action needed.

-- ============================================================
-- SECTION 3: Verification
-- ============================================================
SELECT COUNT(*) FROM cars;
